### ISSUE TITLE
Bring theese guys some beer and pizza!

### ISSUE THREAD

**Issue by zenobius** [tildeio/htmlbars#191]
Hey!

Is there a donation we can do? :-)

A think a lot lot lot of devs are waiting for this to happen (myself and my team included).

Loading >300 records, every one with some metamorph if's, couple of relations, and it's not usable.

It's profiling hell, and it's not getting any better. We're hacking the hell out of handlebars, but we all know it's BS.

So, I'll bring you guys evetyghing you need to code this jewel (well.. ember) just to finish this in the best way you can :-)

Of course this is kind-of haha-issue, but I'm sure I'm not the only one cheering on this thing to be completed, it means a lot to the community :-)

Have a great one!

**Comment by zenobius** [comment]
I've worked on this with my company, and there's possibility that couple of people from my team will be able to work on this project for couple of days a week. We're still looking forward for using this in our project (large lists of complicated models to show ;-) ).

Keep doing the good work :-)

**Comment by mmun** [comment]
Sweet. htmlbars isn't ready for primetime yet. We're still dogfooding the library in Ember. Please join us at #dev-glimmer on the [Ember community slack](https://ember-community-slackin.herokuapp.com/) if you've got any questions! Btw, @krisselden made a demo of dbmonster using pure htmlbars recently. It's pretty fast:

**Comment by zenobius** [comment]
Thanks for the tip, I'll join the community :-)

I can't wait till we can use this in production.
