### ISSUE TITLE
Concat hook called when only one path is provided

### ISSUE THREAD

**Issue by epicmiller** [tildeio/htmlbars#222]
This:
```<div class="{{path}}"></div>```

Will generate this:
```attribute(env, element14, "class", concat(env, [get(env, context, "path")]));```

It calls the concat hook when only a ```get()``` will suffice. When there is only one mustache in an attribute, concat should not be called.

**Comment by mixonic** [comment]
@epicmiller I'm going to close this down. Having quotes to determine string-ness is going to be a lot more meaningful once we look at them in the light of tag-based components. Keep pondering though, we can re-open the discussion as we use the new APIs and learn more about how the act in real codebases.

Thanks! :-)
