### ISSUE TITLE
IE8: Object doesn't support this action

### ISSUE THREAD

**Issue by zyllorion** [tildeio/htmlbars#241]
https://github.com/tildeio/htmlbars/blob/5885113119d28b756baef2a1a185ed51d76f8aa0/packages/morph/lib/dom-helper.js

Ember      : 1.11.0-beta.1+canary.dca9c74d
Ember Data : 1.0.0-beta.14.1
jQuery     : 1.11.2

Line 182: element[normalized] = value;
is not happy when value="type", erroring with "Object doesn't support this action".

**Comment by rwjblue** [comment]
@zyllorion - Can you share a template snippet that causes this error?

**Comment by rwjblue** [comment]
Possibly somewhat related to https://github.com/tildeio/htmlbars/pull/239#issuecomment-68924786 (as we may need to call `setAttribute` on IE if you can't assign to the property).

**Comment by zyllorion** [comment]
@rwjblue Hi, I have tried deleting the template content entirely and it still errors.  I thought it may be an npm dependency or something, but the root route works fine no error (and no content to error on).  It could be either the route mapping which is fairly basic, or the ember-data models.  Either way I think you're right it needs to be parsed to avoid IE8 treating it wrong - the question is where.
Not sure if it's related to https://github.com/tildeio/htmlbars/pull/239#issuecomment-68924786 as it occurs with blank templates.  Will try and do some more digging tomorrow.
Thanks.

**Comment by rwjblue** [comment]
@zyllorion - Can you throw together a quick sample repo (ember-cli is probably the easiest way to go ATM)?

**Comment by oneeman** [comment]
This might well be due to my use of `indexOf` during template compilation.  @salzhrani is working on fixes for IE8, and that was one of the problems.  See https://github.com/tildeio/htmlbars/pull/247.

**Comment by oneeman** [comment]
Oops, sorry about the prior comment (now deleted). I was confused.

**Comment by zyllorion** [comment]
Had to switch to 1.10 beta 4 and get different error now:
Invalid argument.
Which seems to be related to using {{yield}} in block components.  Remove the yield, no error.  Of course it also means no working component :)  Still working to isolate the problem...
