### ISSUE TITLE
IE8 and svg

### ISSUE THREAD

**Issue by salzhrani** [tildeio/htmlbars#246]
It seems that IE 8 doesn't support `createElementNS` or inline svg. what is the best approach to handle this ?
Been trying to make IE8 pass and this is a major issue

**Comment by mixonic** [comment]
@salzhrani the code paths that require createElementNS should not be followed in IE8. An example in tests:

https://github.com/tildeio/htmlbars/blob/master/packages/morph/tests/dom-helper-test.js#L432

And an example in code:

https://github.com/tildeio/htmlbars/blob/master/packages/morph/lib/dom-helper.js#L197

**Comment by oneeman** [comment]
Closing since you already took care of this in your PR :-)
