### ISSUE TITLE
Build Fails When Installed As Another Module's Dependancy

### ISSUE THREAD

**Issue by epicmiller** [tildeio/htmlbars#269]
The build does not finish when htmlbars is a dependency of another npm module. It fails with this error:
```
ENOENT, no such file or directory '/Users/adammiller1/rebound/node_modules/htmlbars/.git/HEAD'
Error: ENOENT, no such file or directory '/Users/adammiller1/rebound/node_modules/htmlbars/.git/HEAD'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at getRevision (/Users/adammiller1/rebound/node_modules/htmlbars/packages/index.js:12:25)
    at Object.<anonymous> (/Users/adammiller1/rebound/node_modules/htmlbars/packages/index.js:26:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```
It is because of the ```getRevision()``` function here:
https://github.com/tildeio/htmlbars/blob/master/packages/index.js#L26

When installed into the node_modules folder as a dependancy, npm does not keep the .git directory and this function fails hard.

**Comment by rwjblue** [comment]
Ember includes this as a dep of a dep (via `emberjs-build`) and it does work properly.

Can you provide more details? How have you referenced it in the `package.json`'s of the various projects?  How are you requiring? etc....

**Comment by rwjblue** [comment]
But we should definitely make the `getRevision` function not blow up if `.git` isn't found.

**Comment by epicmiller** [comment]
What versions of node is ember tested against?

**Comment by rwjblue** [comment]
Also, the main entry point is `dist/cjs/htmlbars.js` (which is a file generated in `npm prepublish`), why require `htmlbars/packages` or `htmlbars/packages/index`?

**Comment by rwjblue** [comment]
@epicmiller - The Ember test suite runs against Node 0.11 I believe.

**Comment by epicmiller** [comment]
Let me update node and npm to the latest and see if it fixes things.

I'm pulling it down at a specific commit and it fails:
```
"dependencies": {
    "htmlbars": "git://github.com/tildeio/htmlbars.git#513c91780d0abb2fc03c91d34e54504490b103e5"
} ```

It will work fine if I use the version in npm

**Comment by rwjblue** [comment]
HTMLBars is not designed to be required via `git` as you have setup here.  The main entry point (which is used when you do something like this: `var htmlbars = require('htmlbars');`) is `dist/cjs/htmlbars.js` which is a file that is generated as part of `npm prepublish`.

**Comment by epicmiller** [comment]
```npm install``` (for some reason) calls ```npm prepublish``` too: https://github.com/npm/npm/issues/3059. So if all of its other dependancies are install it will actually generate the ```/dist``` directory. 

I suppose it would just be a nice-to-have, being able to test htmlbars integration at any specific commit :) That was more important when it was more in flux though I suppose. Feel free to close this if you think its an unnecessary feature!

**Comment by rwjblue** [comment]
'npm install' iwill call the prepublish script only within the htmlbars repo. If you have htmlbars as a dep, then call npm install on that parent repo the htmlbars prepublish is not called.

**Comment by epicmiller** [comment]
Never mind then, you learn something new every day!
