### ISSUE TITLE
Helper syntax documentation/clarification

### ISSUE THREAD

**Issue by thejchap** [tildeio/htmlbars#270]
Prior to HTMLbars things like this would work for defining helpers (this particular example in ember-cli):

```js
import config from 'ui/config/environment';

export function hasFeature(feature) {
	return (window[config.APP.FEATURES_KEY] || {})[feature] === true;
}

export default function (feature, options) {
  return hasFeature(feature) ? options.fn(this) : null;
}
```

Is there documentation somewhere or any discussion as to how to translate this to the new syntax? I was unable to find a clear path.

Happy to contribute docs if there is an answer somewhere and they haven't been written up yet.

Thanks!

**Comment by rwjblue** [comment]
That should still work (we built a compatibility layer).  We should make sure it does.

**Comment by thejchap** [comment]
Got it....here's versions if it's helpful....lmk if you'd like me to make an example repo or something

Ember  : 1.11.0-beta.1+canary.d2d1490d
Ember Data : 1.0.0-beta.15-canary
jQuery  : 2.1.1

**Comment by thejchap** [comment]
Also, FWIW:

```js
Ember.keys(options)
// ["morph", "template", "inverse", "isBlock", "view", "dom", "hooks", "helpers", "data", "hash"]
```

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/10279 to fix.

**Comment by thejchap** [comment]
20 minutes flat....not too shabby...

Haha awesome
