### ISSUE TITLE
Tests broken with `ember serve`

### ISSUE THREAD

**Issue by mmun** [tildeio/htmlbars#272]
I think #265 broke how `ember serve` works. Are we no longer supporting this?

cc @johanneswuerbach

**Comment by rwjblue** [comment]
Yes, @trek has a PR in ember-cli fixing the issue. I will release a new version once that lands.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/3156

**Comment by mmun** [comment]
¡qué alegría!

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/3156 has landed, this issue will be fixed once 0.1.13 is released...

**Comment by mmun** [comment]
Fixed in #293.
