### ISSUE TITLE
IE8 does not set type as a prop

### ISSUE THREAD

**Issue by mixonic** [tildeio/htmlbars#287]
IE8 throws an exception when changing type, at least in some cases (like changing the value from "reset" to "submit").

In the normalize function, we should attempt forcing type to be set with setAttribute, and see if that satisfies IE8 (along with modern browsers).

**Comment by benmoss** [comment]
Even if we change it to use `setAttribute`, IE8 still reports "This command is not supported". It seems it's not possible to change the `type` attribute once it has been set.

**Comment by mixonic** [comment]
@ebryn trololo, you were correct about type as far as IE8 is concerned :-)

Thanks @benmoss

**Comment by idautocfator** [comment]
No IE8 support is what I'm reading here, sort of.
