### ISSUE TITLE
Prebuild files

### ISSUE THREAD

**Issue by riklaunim** [tildeio/htmlbars#298]
Is there a chance for prebuild files? I don't use ember-cli in my apps, and I'm not a fan of npm which is hard to do something without errors on Linux ;)

**Comment by mixonic** [comment]
@riklaunim For HTMLBars, only npm builds are available:

https://www.npmjs.com/package/htmlbars

If you are looking for a way to build Ember templates, use the `ember-template-compiler.js` file. You can find this published with builds:

http://builds.emberjs.com/tags/v1.10.0/ember-template-compiler.js

This blog post is a good resource for building your own compiler:

http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html

I'll close this as I think that covers it, but feel free to re-open if I've missed anything!
