### ISSUE TITLE
IE11 throws exception when setting input type to date

### ISSUE THREAD

**Issue by karl-sjogren** [tildeio/htmlbars#321]
We just upgraded to Ember 1.11.1 and instantly started seeing exceptions thrown on IE11. It seems that when we use an input-helper with type="date" IE throws an "Invalid argument" exception in setPropertyStrict in dom-helper.js (https://github.com/tildeio/htmlbars/blob/master/packages/dom-helper/lib/main.js#L253).

I created a quick jsbin to reproduce the problem.

http://emberjs.jsbin.com/liqiwarosi/1/

**Comment by stefanpenner** [comment]
can you re-confirm now? ember 1.13.3 has been released (or will momentarily) with lots of fixes in this area.

**Comment by rwjblue** [comment]
Ember addressed this in 1.12.0 (with https://github.com/emberjs/ember.js/pull/10690).

Not much can be done here in HTMLBars, or with 1.11.0 so I'm going to close this...

**Comment by karl-sjogren** [comment]
Yes rwjblue is right but to be a good reporter I checked it anyways with a new JSBin for 1.13.3 and it worked fine in both IE11 and Edge.

http://emberjs.jsbin.com/feyidusujo/1/edit?html,css,js,output
