### ISSUE TITLE
each helper cannot iterate over objects

### ISSUE THREAD

**Issue by leejt489** [tildeio/htmlbars#322]
In Handlebars, we could iterate over an object with key/value pairs.  In HTMLbars I get the error `Uncaught Error: Assertion Failed: The value that #each loops over must be an Array. You passed {prop1: prop1Value, prop2: prop2Valuel} `

By design or bug?

**Comment by mmun** [comment]
Are you referring to Ember's #each helper? You should search for / report an issue there.

**Comment by leejt489** [comment]
Cool, thought it was HTMLbars because it used to work when Ember was using Handlebars but I guess it is an ember issue.

**Comment by hcatlin** [comment]
+1 for this... kind of weird I can't do that...

**Comment by rwjblue** [comment]
@hcatlin - There is a recent PR in ember adding {{each-in}} helper for iterating objects. It will be feature flagged, but is likely to be available in 2.0.0 (which should hit beta around 4 weeks from now).
