### ISSUE TITLE
Using the less than less than operator in script tag is incorrectly parsed 

### ISSUE THREAD

**Issue by ryanhollister** [tildeio/htmlbars#326]
Appears that htmlbars is incorrectly parsing javascript blocks when there is a '<' operator in the block:

http://emberjs.jsbin.com/jocafazaxa/1/edit?html,js,console

Expected behavior here would be that the sort function is available on the window object.

Note that changing the operator to a '>' works fine.

**Comment by mmun** [comment]
We don't have plans to support this.

**Comment by ryanhollister** [comment]
Appreciate you taking the time to look. But to be clear for future reference, what is it you are not planning to support? Less than operators in script tags?

**Comment by mmun** [comment]
Sorry. I mean we only intended to support HTML that 1. Goes inside the <body> tag 2. has no <script> tags.

**Comment by matthewrobb** [comment]
What about this case? http://emberjs.jsbin.com/feyuse/1/edit?html,js,console

**Comment by mmun** [comment]
Yeah, that's a bug in https://github.com/tildeio/simple-html-tokenizer.
