### ISSUE TITLE
Flesh out the AST walker

### ISSUE THREAD

**Issue by mmun** [tildeio/htmlbars#339]

**Comment by Cheralyn** [comment]
This is an automatically generated message.

coferc@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!
