### ISSUE TITLE
inline hook doesn't update morph to false-like values

### ISSUE THREAD

**Issue by jmurphyau** [tildeio/htmlbars#348]
The below block of code in the inline hook causes issues when a false-like value is returned.

If `morph.lastValue` is `hello` and you want to update the value to a blank value (e.g. null or '') the check `result && result.value` stops the value from actually being updated.

    if (result && result.value) {
      var value = result.value;
      if (morph.lastValue !== value) {
        morph.setContent(value);
      }
      morph.lastValue = value;
    }

In the new Ember {{get}} keyword there is a particular [workaround](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/keywords/get.js#L28) in place to compensate for this issue.

**Comment by rwjblue** [comment]
It should be `result && 'value' in result`.  Would you mind making a PR with a test?
