### ISSUE TITLE
Seeking documentation - what operators are allowed?

### ISSUE THREAD

**Issue by stefek99** [tildeio/htmlbars#368]
I tried searching:
* https://www.google.com/#q=htmlbars+expressions
* https://www.google.com/#q=htmlbars+logic+in+templates
* https://www.google.com/#q=htmlbars+and+or+operators

Found this presentation: http://oscarlodriguez.nl/Labs/htmlbars/#/8
![image](https://cloud.githubusercontent.com/assets/249703/8062006/6b3d6e2e-0ec5-11e5-9d5e-5c008613e39f.png)

But it doesn't tell me much about the syntax.

My current code:
```
<div class="flags {{if submission.approved 'hidden'}} {{if submission.rejected 'hidden'}}">

</div>
```

I want to add class ```hidden``` whenever submission has been approved or rejected.

---

I would like to know which operators works out of the box, what is the syntax and how to write own helpers as described here: http://stackoverflow.com/questions/8853396/logical-operator-in-a-handlebars-js-if-conditional

**Comment by salzhrani** [comment]
Better use a computed property `Ember.computed.or`

**Comment by mixonic** [comment]
Or alternatively this excellent addon: https://github.com/jmurphyau/ember-truth-helpers

These helpers are not provided "out of the box", without an addon you would need to create a computed property. There are no immediate plans to add utility helpers like `or`, but we will be considering it later in the year.

This will be better documented as the Guides for ember are updated around 2.0. I'm closing this as I believe it is actually an issue with Ember's documentation, and unrelated to HTMLBars itself.

**Comment by stefek99** [comment]
OK, thank you for letting me know.
