### ISSUE TITLE
Implement Google's Incremental DOM

### ISSUE THREAD

**Issue by adamzr** [tildeio/htmlbars#405]
Use [Google's New Incremental DOM](https://github.com/google/incremental-dom) as the backend for rendering. This will allow using its patch function to make re-rendering more efficient.

**Comment by mixonic** [comment]
@adamzr "more efficient" seems to be a large assumption? Do you see a specific improvement that Incremental DOM brings to the HTMLBars rendering algorithm? It is new, and interesting. I'm not sure that means we should undertake a massive re-write to leverage it.

**Comment by stefanpenner** [comment]
A quick read, suggests this solves something Orthogonal. HTMLBars never diffs trees of DOM, or VDom (like react and friends). Instead it applies patches to the existing DOM. It does so after detecting changes in the streams of data the populate the dom.

**Comment by matthewrobb** [comment]
I've followed HTMLBars pretty closely for a decently long time and I have also been following IncrementalDOM since it's announcement. I'm by no means an expert on either but I do believe that the methods used for applying changes to the DOM are very similar in nature between these two projects.

It's probably much too early but it seems reasonable at some future point that some commonalities could become a shared substrate.

**Comment by wycats** [comment]
@matthewrobb there is a lot in common between these two solutions, but there is something fundamentally different between the approaches.

Incremental DOM has an API that looks like this:

```js
var IncrementalDOM = require('incremental-dom'),
    elementOpen = IncrementalDOM.elementOpen,
    elementClose = IncrementalDOM.elementClose,
    elementVoid = IncrementalDOM.elementVoid,
    text = IncrementalDOM.text;

function render(data) {
  elementVoid('input', '', [ 'type', 'text' ]);
  elementOpen('div', '', null);
    if (data.someCondition) {
      text(data.text);
    }
  elementClose('div');
}
```

When you run an operation (like `elementVoid`), if you are running the same operation as last time, it knows it doesn't have to do any work.

**However**, you still have to run the above code on every rerender (the incremental DOM strategy just makes it faster to determine what the changes are than the equivalent Virtual DOM code).

HTMLBars works differently. The compiler divides up the work between static areas and dynamic areas.

Let's consider the Handlebars equivalent of the incremental DOM example:

```hbs
<input type="text">
<div>{{#if someCondition}}{{text}}{{/if}}</div>
```

For this template, we will get a template with two parts:

1. `buildFragment` will build the `<input>`, `<div>`, and insert a placeholder for the `{{#if}}` and its child `{{text}}`.
2. the rendering process describes how to fill in the placeholders.

On initial render, we run both (1) and (2). On re-renders, we **only run (2)**. This means that re-renders do not even need to do the work Incremental DOM is doing to discover that the calls to `elementVoid` and `elementOpen` are the same as they were the first time.

The cool thing about both Virtual DOM and Incremental DOM is that they shrink the amount of work you need to do to discover "no work" dramatically from what you would naively expect. The latest optimizations in Babel are targeted at exactly this: how can we make the comparison as fast as possible.

In contrast, the strategy of HTMLBars/Glimmer is to **not actually run any code related to the static parts on re-render.** It may well turn out that a highly tuned Virtual DOM or Incremental DOM gets pretty close to that strategy, especially with a modern JIT, but I still prefer not to run any code ([No code is faster than no code](https://en.wikipedia.org/wiki/Merb)).

**Comment by S-YOU** [comment]
Thanks for the detailed explanations @wycats. Glad I subscribed repo.  What technique do you use for placeholders, btw? comment nodes?

**Comment by matthewrobb** [comment]
@wycats Just curious couldn't it be possible to do that static analysis and produce code that builds the whole dom tree the first time through but skips the static parts there after? It seems like idom doesn't really PREVENT you from doing smaller patch operations on sub sections of a built tree.

**Comment by stefanpenner** [comment]
@matthewrobb unless I misread what you meant, that describes what htmlbars does.

**Comment by mmun** [comment]
@S-YOU Yes, primarily comment nodes with some empty text nodes sprinkled in.

**Comment by S-YOU** [comment]
Thanks for the info @mmun.

**Comment by matthewrobb** [comment]
@stefanpenner If that is the case (and if I am understanding the right way) then it seems like the primary difference between htmlbars and idom is that htmlbars incorporates a built in model for an efficient output target, correct?

**Comment by wycats** [comment]
> htmlbars incorporates a built in model for an efficient output target, correct?

Can you say more about what you mean by this?

**Comment by matthewrobb** [comment]
I guess it just seems like considering idom a compile target you could output code that never tries to rerender the static portions of a template and instead does small patch operations on the dynamic portions for all subsequent changes. It seems like that efficiency all comes from the compiler and not from the runtime per se.

**Comment by stefanpenner** [comment]
@matthewrobb what you describe, if I understood you correctly, is what htmlbars does.

**Comment by stefanpenner** [comment]
Also note, I am not implying there isn't something that can't be learned from idom. Rather the points raised are already competencies of htmlbars.

**Comment by matthewrobb** [comment]
@stefanpenner I'm sorry about the confusion. I was just trying to clarify my own understanding. It sounds like we're on the same page now.

My take away is that in theory idom could be just as efficient as htmlbars if compiled correctly (or I guess written by hand that way).

**Comment by stefanpenner** [comment]
Ah ok

**Comment by S-YOU** [comment]
Just FYI, while I am adding Incremental DOM to a benchmark today based on  https://twitter.com/tomdale/status/424247991780659200.

I noticed it has similar speed between Ember/HTMLBars and Incremental DOM. http://rawgit.com/S-YOU/doTA/master/examples/animate-circles/index.html  (_which includes my experimental library too, pls ignore that._)

**Comment by atomictag** [comment]
Although this is an old and closed thread, in case anybody is still interested I have just published `incremental-bars`, a library that allows to use incremental-dom with Handlebars templates.

You can check it out [here](https://github.com/atomictag/incremental-bars).
