### ISSUE TITLE
{{link-to}} "disabledWhen" documentation wrong?

### ISSUE THREAD

**Issue by Fryie** [tildeio/htmlbars#413]
According to [the documentation](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_link-to), ```{{link-to}}``` should work with a ```disabledWhen``` attribute that is evaluated dynamically (as opposed to the "static" ```disabled``` attribute). This also used to work in Ember 1.12. However, it doesn't seem to work as advertised: http://ember-twiddle.com/4bcac030ed2c19272271

Changing ```disabledWhen``` to ```disabled``` seems to work, however, and doesn't seem to be "static" at all (maybe I'm misunderstanding the labels static and dynamic here?).

**Comment by jcope2013** [comment]
related? https://github.com/emberjs/ember.js/pull/12344

**Comment by rwjblue** [comment]
@jcope2013 is correct, https://github.com/emberjs/ember.js/pull/12344 fixed the issue in the Ember release-1-13 branch. So I'm going to go ahead and close...

**Comment by Fryie** [comment]
sorry, just to follow up: in which release is this fixed? 'cause i'm running ember 1.13.7.

**Comment by jcope2013** [comment]
@Fryie add ``` "ember": "#release-1-13" ``` to your bower.json to get it now, it will be included in 1.13.11 but you can get it now by using the release branch

**Comment by Fryie** [comment]
sweet, thanks a lot

**Comment by Fryie** [comment]
just to clarify, though: why does the syntax with "disabled" work, even though it's supposed to be "static" as per the docs? is that also part of the fixed bug?

**Comment by Fryie** [comment]
just to answer my own question, "disabled" only seems to work: it creates the right css class, so the link looks disabled, but it's actually clickable. I'll try updating ember and changing back to "disabledWhen". :)
