### ISSUE TITLE
script content

### ISSUE THREAD

**Issue by g13013** [tildeio/htmlbars#426]
It seems that HTMLbars tries to parse a script tag content, and issues this error

```
[Error: Unclosed element `data.length;` (on line 32).] 
```

When I remove the script tag it compiles without error !

**Comment by mmun** [comment]
Script tags are not supported.

**Comment by stefanpenner** [comment]
> We should improve the error.

:+1:

**Comment by mmun** [comment]
I've created a quest issue #427 for anyone who's interested in fixing this.

**Comment by g13013** [comment]
thanks @mmun @stefanpenner, i am interested in fixing it, but i do not understand how htmlbars works internally 😱

**Comment by g13013** [comment]
@mmun now that I read the steps i understand that it will not be supported, right ?

**Comment by mmun** [comment]
@g13013 That's right. It will not be supported. It's not clear what the semantics of "rendering" a script would be anyways. What does this even mean?

```hbs
<script>
  console.log("{{message}}");
</script>
```

**Comment by g13013** [comment]
@mmun I understand the reasons.
I think that at least content of `<style>` and `<script>` should be ignored and inserted as is. not parsing  and no dynamic value.
