### ISSUE TITLE
get helper silently fails to access number-like keyed items

### ISSUE THREAD

**Issue by barneycarroll** [tildeio/htmlbars#440]
I thought this was an issue with 'linked' Arrays, but it seems to be more complicated than that. [See this twiddle](https://ember-twiddle.com/7f7053c4402f258fa38f):

```javascript
export default Ember.Controller.extend({
  numbers:['1','2','3','4'],
  letters:{ '0':'a', '1':'b', '2':'c', '3':'d' }
});
```
```handlebars
{{#each numbers as | value index |}}
	{{my-component 
  	number=value
    letter=(get letters index)
  }}
{{/each}}
```

**Comment by rwjblue** [comment]
The `get` helper is implemented in Ember itself (not HTMLBars), so this is likely an issue over there.

**Comment by barneycarroll** [comment]
Oops! Thanks. I misread the test as the implementation :)
