### ISSUE TITLE
HTMLBars not respecting Ember.String.htmlSafe()

### ISSUE THREAD

**Issue by spinlock99** [tildeio/htmlbars#452]
If I bind to the variable `message` in a template:

    //template.hbs
    {{message}}

    //component.js
    message: "line one<br>line two"

`message` will be escaped and the `<br>` tag will not cause a line break. However, if the variable is a SafeString, it is still escaped:

    //component.js
    message: Ember.String.htmlSafe("line one<br>line two")

**Comment by rwjblue** [comment]
Could you please provide a demo/reproduction?

**Comment by spinlock99** [comment]
OK, I'm an idiot. I was trying to compose multiple htmlSafe strings and pass that as `message`. If I compose the string then call `htmlSafe` it works.

Thanks.
